package com.example.travel.audit.entity;

public enum AuditAction {
    USER_REGISTERED,
    USER_CREATED_BY_ADMIN,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    USER_STATUS_CHANGED,
    TRIP_CREATED,
    TRIP_UPDATED,
    TRIP_CANCELLED,
    TRAVELER_ADDED,
    TRAVELER_UPDATED,
    TRAVELER_REMOVED,
    FLIGHT_ADDED,
    FLIGHT_UPDATED,
    FLIGHT_REMOVED,
    HOTEL_ADDED,
    HOTEL_UPDATED,
    HOTEL_REMOVED
}
